# PhongPhung
# Email: phongifls@gmail.com
# Linked in: www.linkedin.com/in/phong-phung/
# Phone: +84 1268900219
# -------------------------------------------
data:
  FOLDER: Data
  FILE_NAME: data.csv
  FILE_TYPE: CSV # CSV XLSX
  ENCODING: ISO-8859-1
  SEP: ','
  COLUMN: url

settings:
  THREADS: 20
  PROCESSES: 8

database:
  LOCAL_DB: "dbname='crawler' user='postgres' host='localhost' password='motsach' port=5432"
  CRAWL_TABLE: David1
  DATA_TABLE: DavidData
  SCHEMA: crawl01
  TEMP_DATA_TABLE: tmp_table
  BUFFER_SIZE: 200 # in mb
  TIMEOUT: 100 # in second
  RETRY_CONNECT: 3 # times

download:
  OUTSTANDING: 0
  PROCESSING: 1
  COMPLETE: 2
  ERROR: 3

other:
  WAIT_AT_END: 10 # in sec
  USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
               AppleWebKit/537.36 (KHTML, like Gecko)
               Chrome/61.0.3163.100 Safari/537.36'
  VERSION: '1.0.0'

WAIT_AT_END: 300